new fix

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -2,6 +2,9 @@
 # Fixes the nginx listening port and reloads the nginx master process
 sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
 sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
-pgrep nginx -o > /run/nginx.pid
-nginx -s reload
-echo '' > /run/nginx.pid
+nginx -t                  # Test the nginx configuration for syntax errors
+if [ $? -eq 0 ]; then
+    nginx -s reload        # Reload nginx if the configuration is valid
+else
+    echo "Nginx configuration test failed. Not reloading."
+fi
